Algoritmo "Olé Mundo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi // Gustavo Guanabara
// Descrição   : Programa para dizer: "Olá Mundo"! (função)
// Autor(a)    : Atson Ferreira de Melo
// Data atual  : 10/06/2023
Var

Inicio
   Escreval("Olá mundo!")
   Escreval("Estou grato por poder estar aqui aprendendo.")
   Escreva("O Senhor é o meu pastor, nada me faltará. Salmos 23.1")

Fimalgoritmo
